local o = vim.opt

o.clipboard = "unnamedplus"
o.cmdheight = 2
o.backup = false
o.background = "dark"
o.number = true
o.relativenumber = false
o.mouse = "a"
o.colorcolumn = {81}
o.textwidth = 81
o.expandtab = false
o.tabstop = 4
o.shiftwidth = 4
o.completeopt = { "menuone", "noselect" }
o.scrolloff = 8
o.sidescrolloff = 8
o.cursorline = true
o.undofile = true
o.smartcase = true
o.smartindent = true
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.updatetime = 300
o.signcolumn = "yes"
o.fileencoding = "utf-8"
o.hlsearch = true
o.ignorecase = false
o.pumheight = 10
o.showmode = false
o.updatetime = 300
