require "default.options"
require "default.keymaps"
require "default.plugins"
require "default.colorscheme"
require "default.completion"
require "default.lsp"
require "default.telescope"
--require "default.treesitter"
